# Publish all joint states -----------------------------------
spin_joint_states:
  type: joint_state_controller/JointStateController
  publish_rate: 200


spin_joint_vel_controller:
  type: "velocity_controllers/JointVelocityController"
  joint: lidar_spin_joint